using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rpgwo_Server.Networking
{
    public enum PacketTypes : byte
    {
        Nack = 0,
        Version = 2,
        Login = 4,
        Create = 5,
        ReqPlayerList = 6,
        PlayerList = 7,
        Logout = 8,
        Delete = 9,
        MapData = 10,
        Enter = 11,
        EnterFinal = 12,
        ExitWorld = 13,
        MovePlayer = 14,
        StartDisplay = 15,
        StopDisplay = 16,
        PlayerLocation = 17,
        ItemLocation = 19,
        WorldState = 22,
        MapLineData = 24,
        StartLineDisplay = 25,
        PlayerStats = 27,
        ReqClientList = 28,
        ClientList = 29,
        Attack = 30,
        RaiseAttribute = 31,
        RaiseSkill = 32,
        Event = 33,
        Sound = 34,
        Skill = 36,
        Attributes = 37,
        ReqSkillList = 38,
        TrainSkill = 39,
        MoveItem = 40,
        Text = 41,
        UseItem = 42,
        PlayerStats2 = 43,
        StatCheck = 47,
        SelfDestruct = 48,
        PlayerInfo2 = 52,
        UntrainSkill = 53,
        RequestAppeal = 55,
        Appeal = 56,
        AppealDel = 57,
        Cast = 58,
        SpellTest = 60,
        SpellDef = 61,
        RuneBag = 62,
        DropRune = 63,
        CreateDef = 65,
        SkillDef = 67,
        ReqSkillDef = 68,
        SpellDelete = 69,
        Animation2 = 70,
        CheckItem = 71,
        MonsterLocation = 72,
        RandomByte = 73,
        Projectile = 74,
        Mail = 77,
        Info2 = 90,
        Info3 = 91,
        Request = 101,
        Result = 102,
        Ack = 255
    }
}
